name: Deploy Next.js to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy Next.js to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: 13.60.74.228
          username: ubuntu
          key: ${{ secrets.PRIVATE_VM_SSH }}
          port: 22
          script: | 
            cd 100x-ci-cd
            git pull origin main
            npm install
            npm run build
            npm run start